export const PROCUREMENT_PROP_VALUES = {
"department": [
  "Main Hall",
  "Cowork",
  "Art Room",
  "Fun Room",
  "Patio",
  "Workshops",
  "Pool",
  "Garden",
  "General",
  "Kitchen",
  "Office",
  "Cashier"
] as const,
"tags": [
  "Pay To Play",
  "Sample"
] as const,
"paidFrom": [
  "Yarden (cash)",
  "Ohad (Cash)",
  "Yarden (Poalim)",
  "Ohad (Thai Bank)"
] as const,
"objectCategory": [
  "Kids Safety",
  "Kitchen Equipment",
  "Furniture",
  "Outdoor Playground",
  "Pretend Play",
  "Gross Motor",
  "Soft Play",
  "Storage",
  "STEM",
  "Lego",
  "Educational",
  "Building Blocks",
  "Garden maintenance",
  "Once",
  "Board Game",
  "Thinking / Puzzle",
  "Montessori Toy",
  "Toddler Book",
  "Stuffed Toys",
  "1 on 1 Game",
  "Toddler Toys",
  "Cooling & Ventilation",
  "Play Together",
  "Decoration",
  "Arts & Crafts",
  "caffee",
  "Curtains",
  "Display",
  "Logistics"
] as const,
"status": [
  "Out Of Stock",
  "Idea",
  "Research",
  "Negotiating",
  "Quoted",
  "Approved",
  "Ordered",
  "Shipped",
  "Arrived",
  "Installed",
  "Archived"
] as const,
}

export const PROCUREMENT_PROPS_TO_IDS = {
  "supplier": "%3AasX",
  "parentItem": "ByA%3F",
  "link": "D%7DIr",
  "trackingNumber": "G%7DHG",
  "department": "U%60kx",
  "notes": "WP%3Ev",
  "invoice": "%5C%5DWc",
  "tags": "aSo%3B",
  "totalPrice": "dGR%7C",
  "priceThb": "eug%5C",
  "subItem": "iSMi",
  "paidFrom": "jPNR",
  "image": "k%3Bz%3C",
  "price_1010": "sb%3Dq",
  "quantity": "uz%3En",
  "objectCategory": "wI%60N",
  "status": "~NX%5B",
  "item": "title",
  "createdBy": "%3DKtU",
  "lastEditedBy": "%40rim",
  "createdTime": "%5DhP%3F",
  "lastEditedTime": "ak%7BJ"
} as const
export const PROCUREMENT_IDS_TO_PROPS = {
  "%3AasX": "supplier",
  "ByA%3F": "parentItem",
  "D%7DIr": "link",
  "G%7DHG": "trackingNumber",
  "U%60kx": "department",
  "WP%3Ev": "notes",
  "%5C%5DWc": "invoice",
  "aSo%3B": "tags",
  "dGR%7C": "totalPrice",
  "eug%5C": "priceThb",
  "iSMi": "subItem",
  "jPNR": "paidFrom",
  "k%3Bz%3C": "image",
  "sb%3Dq": "price_1010",
  "uz%3En": "quantity",
  "wI%60N": "objectCategory",
  "~NX%5B": "status",
  "title": "item",
  "%3DKtU": "createdBy",
  "%40rim": "lastEditedBy",
  "%5DhP%3F": "createdTime",
  "ak%7BJ": "lastEditedTime"
} as const
export const PROCUREMENT_PROPS_TO_TYPES = {
  "supplier": "relation",
  "parentItem": "relation",
  "link": "rich_text",
  "trackingNumber": "rich_text",
  "department": "multi_select",
  "notes": "rich_text",
  "invoice": "files",
  "tags": "multi_select",
  "totalPrice": "formula",
  "priceThb": "number",
  "subItem": "relation",
  "paidFrom": "select",
  "image": "files",
  "price_1010": "number",
  "quantity": "number",
  "objectCategory": "multi_select",
  "status": "status",
  "item": "title",
  "createdBy": "created_by",
  "lastEditedBy": "last_edited_by",
  "createdTime": "created_time",
  "lastEditedTime": "last_edited_time"
} as const

  export type ProcurementDTOProperties = keyof typeof PROCUREMENT_PROPS_TO_IDS
  