ALTER TABLE IF EXISTS "email_classification_rules"
  ADD COLUMN IF NOT EXISTS "dummy_input" jsonb;
--> statement-breakpoint
-- Seed default classification rules (mirrors src/lib/server/email-automation/seed-rules.ts).
-- Keep this INSERT in sync with SEED_CLASSIFICATION_RULES in that file.
-- The seed only runs when the table is empty, so re-applying the migration is safe
-- and manually-added rules are never clobbered.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM "email_classification_rules" LIMIT 1) THEN
    INSERT INTO "email_classification_rules"
      ("enabled", "priority", "name", "classification", "subtype", "sender_pattern", "subject_pattern", "body_patterns", "handler_key", "ledger_defaults", "notify_policy", "dummy_input")
    VALUES
      (true, 10, 'Approved companion message', 'ignore', 'approved_shadow', 'kasikornbank.com', 'regex:Status .*\(Approved\)', '[]'::jsonb, 'none', '{}'::jsonb, 'never', '{"receivedAt":"2026-07-07T17:51:30.000Z","from":"K BIZ <KBIZ@kasikornbank.com>","to":"automations@casalumakpg.com","subject":"Status of Promptpay Funds Transfer (Approved)","messageId":"<seed-approved-shadow@example.test>","attachmentCount":0,"textBody":"Reference Number: PPFS260707254721403 Amount (THB): 4,000.00"}'::jsonb),
      (true, 20, 'Bill payment / top-up success', 'expense', 'bill_payment_success', 'kasikornbank.com', 'regex:Result of Bill Payment/Top-Up \(Success\)', '[]'::jsonb, 'company_ledger_expense', '{"bankAccount":"KBank"}'::jsonb, 'review_and_success', '{"receivedAt":"2026-07-09T10:06:05.000Z","from":"K BIZ <KBIZ@kasikornbank.com>","to":"automations@casalumakpg.com","subject":"Result of Bill Payment/Top-Up (Success)","messageId":"<seed-bill-payment-success@example.test>","attachmentCount":0,"textBody":"Reference Number: BILS260709267019809 Amount (THB): 5,776.31"}'::jsonb),
      (true, 30, 'Other-bank transfer success', 'expense', 'other_bank_transfer_success', 'kasikornbank.com', 'regex:Result of Other Account Funds Transfer \(Other Bank\) \(Success\)', '[]'::jsonb, 'company_ledger_expense', '{"bankAccount":"KBank"}'::jsonb, 'review_and_success', '{"receivedAt":"2026-07-09T10:03:54.000Z","from":"K BIZ <KBIZ@kasikornbank.com>","to":"automations@casalumakpg.com","subject":"Result of Other Account Funds Transfer (Other Bank) (Success)","messageId":"<seed-other-bank-success@example.test>","attachmentCount":0,"textBody":"Reference Number: TRTS260709267002259 Amount (THB): 1,025.00"}'::jsonb),
      (true, 40, 'PromptPay transfer success', 'expense', 'promptpay_transfer_success', 'kasikornbank.com', 'regex:Result of PromptPay Funds Transfer \(Success\)', '[]'::jsonb, 'company_ledger_expense', '{"bankAccount":"KBank"}'::jsonb, 'review_and_success', '{"receivedAt":"2026-07-07T17:51:30.000Z","from":"K BIZ <KBIZ@kasikornbank.com>","to":"automations@casalumakpg.com","subject":"Result of PromptPay Funds Transfer (Success)","messageId":"<seed-promptpay-success@example.test>","attachmentCount":0,"textBody":"Reference Number: PPFS260707254721403 Amount (THB): 4,000.00"}'::jsonb),
      (true, 50, 'K SHOP settlement failure', 'review', 'kshop_settlement_failed', 'kasikornbank.com', NULL, '{"mode":"all","patterns":["regex:could not be deposited|deposit.*failed","regex:K\\s*SHOP"]}'::jsonb, 'notify_only', '{}'::jsonb, 'review_only', '{"receivedAt":"2026-07-08T08:00:00.000Z","from":"KSHOP <KPLUSSHOP@kasikornbank.com>","to":"automations@casalumakpg.com","subject":"เรียน ร้านค้า K SHOP CASA LUMA","messageId":"<seed-kshop-settlement-failed@example.test>","attachmentCount":0,"textBody":"The settlement amount could not be deposited. K SHOP settlement is pending review."}'::jsonb),
      (true, 60, 'Merchant fee failure', 'review', 'merchant_fee_failed', 'kasikornbank.com', NULL, '{"mode":"all","patterns":["regex:fee.*(?:failed|unsuccessful)|(?:failed|unsuccessful).*fee","regex:merchant"]}'::jsonb, 'notify_only', '{}'::jsonb, 'review_only', '{"receivedAt":"2026-07-08T08:00:00.000Z","from":"K-MERCHANT FEE <K-MERCHANT_FEE@kasikornbank.com>","to":"automations@casalumakpg.com","subject":"แจ้งเตือนการชำระค่าธรรมเนียมรายเดือนเครื่อง EDC/mini EDC ไม่สำเร็จ","messageId":"<seed-merchant-fee-failed@example.test>","attachmentCount":0,"textBody":"The monthly merchant fee was unsuccessful. EDC fee failed and needs review."}'::jsonb),
      (true, 70, 'Security / admin / OTP', 'ignore', 'security_or_admin', 'kasikornbank.com', NULL, '{"mode":"any","patterns":["otp","login","regex:sign.?in","email address change","terms of service"]}'::jsonb, 'none', '{}'::jsonb, 'never', '{"receivedAt":"2026-07-08T09:00:00.000Z","from":"K BIZ <KBIZ@kasikornbank.com>","to":"automations@casalumakpg.com","subject":"Notification for login to K BIZ (via K BIZ Web/K BIZ Application)","messageId":"<seed-security-or-admin@example.test>","attachmentCount":0,"textBody":"Login notification. One Time Password (OTP) for K BIZ access."}'::jsonb),
      (true, 80, 'Statement / e-document / renewal', 'review', 'statement_or_attachment', NULL, NULL, '{"mode":"any","patterns":["statement","e-document","subscription renewal"]}'::jsonb, 'notify_only', '{}'::jsonb, 'review_only', '{"receivedAt":"2026-07-01T08:00:00.000Z","from":"K-eDocument <K-ElectronicDocument@kasikornbank.com>","to":"automations@casalumakpg.com","subject":"E-document (K-Deposit Statement) for the period of June 1, 2026-June 30, 2026.","messageId":"<seed-statement-or-attachment@example.test>","attachmentCount":0,"textBody":"Your e-document statement is now available for download."}'::jsonb);
  END IF;
END $$;
