export const EMPLOYEES_PROP_VALUES = {
"languages": [
  "English",
  "Myanmar",
  "Thai",
  "English Little Bit"
] as const,
"employmentType": [
  "Full-time",
  "Part-time",
  "Contract",
  "Temporary",
  "Seasonal",
  "Freelance"
] as const,
"department": [
  "Maintenance",
  "Café",
  "Open Play",
  "Marketing",
  "Management"
] as const,
"nationality": [
  "Burmese",
  "Thai"
] as const,
"paymentFrequency": [
  "Monthly",
  "Bi-weekly",
  "Weekly",
  "Daily",
  "Hourly"
] as const,
"employmentStatus": [
  "Onboarding",
  "Working",
  "Active",
  "Resigned",
  "Terminated",
  "Contract Ended"
] as const,
"salaryCalculation": [
  "Monthly",
  "Daily"
] as const,
}

export const EMPLOYEES_PROPS_TO_IDS = {
  "visaExpiry": "%3CK%5BF",
  "workPermitExpiry": "%3D%3EfR",
  "photo": "%3FOvv",
  "salaryThb": "%3FdnC",
  "languages": "B%5C%7BK",
  "employmentType": "Bop%3E",
  "department": "HpjN",
  "endDate": "KpQj",
  "nationality": "MUL%3E",
  "whatsAppLine": "PPRm",
  "workPermitNumber": "QVjs",
  "email": "Xtg%3C",
  "paymentFrequency": "Z%60%60%5E",
  "fullName": "dNc~",
  "documents": "deEH",
  "address": "dw%7Bq",
  "notes": "gdZF",
  "bankAccountDetails": "jNcC",
  "phone": "lJ%7CL",
  "hometown": "pi%5Dw",
  "employmentStatus": "vCD%5E",
  "reportsTo": "wUr%5B",
  "startDate": "zLrJ",
  "nickname": "title",
  "taxId": "%3FRoK",
  "idPassportNo": "IaO%3B",
  "dateOfBirth": "tIHh",
  "workPermitScan": "Z%5ECt",
  "scanQr": "y%5EAY",
  "salaryCalculation": "UqIQ",
  "otRateThBhr": "pe~h",
  "role": "o%5DfK"
} as const
export const EMPLOYEES_IDS_TO_PROPS = {
  "%3CK%5BF": "visaExpiry",
  "%3D%3EfR": "workPermitExpiry",
  "%3FOvv": "photo",
  "%3FdnC": "salaryThb",
  "B%5C%7BK": "languages",
  "Bop%3E": "employmentType",
  "HpjN": "department",
  "KpQj": "endDate",
  "MUL%3E": "nationality",
  "PPRm": "whatsAppLine",
  "QVjs": "workPermitNumber",
  "Xtg%3C": "email",
  "Z%60%60%5E": "paymentFrequency",
  "dNc~": "fullName",
  "deEH": "documents",
  "dw%7Bq": "address",
  "gdZF": "notes",
  "jNcC": "bankAccountDetails",
  "lJ%7CL": "phone",
  "pi%5Dw": "hometown",
  "vCD%5E": "employmentStatus",
  "wUr%5B": "reportsTo",
  "zLrJ": "startDate",
  "title": "nickname",
  "%3FRoK": "taxId",
  "IaO%3B": "idPassportNo",
  "tIHh": "dateOfBirth",
  "Z%5ECt": "workPermitScan",
  "y%5EAY": "scanQr",
  "UqIQ": "salaryCalculation",
  "pe~h": "otRateThBhr",
  "o%5DfK": "role"
} as const
export const EMPLOYEES_PROPS_TO_TYPES = {
  "visaExpiry": "date",
  "workPermitExpiry": "date",
  "photo": "files",
  "salaryThb": "number",
  "languages": "multi_select",
  "employmentType": "select",
  "department": "select",
  "endDate": "date",
  "nationality": "select",
  "whatsAppLine": "rich_text",
  "workPermitNumber": "rich_text",
  "email": "email",
  "paymentFrequency": "select",
  "fullName": "rich_text",
  "documents": "files",
  "address": "rich_text",
  "notes": "rich_text",
  "bankAccountDetails": "rich_text",
  "phone": "phone_number",
  "hometown": "rich_text",
  "employmentStatus": "status",
  "reportsTo": "people",
  "startDate": "date",
  "nickname": "title",
  "taxId": "rich_text",
  "idPassportNo": "rich_text",
  "dateOfBirth": "date",
  "workPermitScan": "files",
  "scanQr": "files",
  "salaryCalculation": "select",
  "otRateThBhr": "formula",
  "role": "relation"
} as const

  export type EmployeesDTOProperties = keyof typeof EMPLOYEES_PROPS_TO_IDS
  